// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-gaurd/api/controller/public"
	"go-gaurd/core/config"
	"go-gaurd/database"
	"go-gaurd/feature/auth/domain"
	"go-gaurd/feature/auth/usecase"
)

// Injectors from wire.go:

func InitializeAuthApplication() (*public.AuthController, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	authRepository := domain.NewAuthRepository(databaseDatabase)
	authUseCase := usecase.NewAuthUseCase(authRepository)
	redisCache, err := database.NewRedisCache(configConfig)
	if err != nil {
		return nil, err
	}
	authController := public.NewAuthController(authUseCase, redisCache)
	return authController, nil
}
